version: "3"
services:
  postgres:
    container_name: database_postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=aroot
    ports:
      - "5433:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d